# Generated by Django 5.1 on 2024-08-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('program', models.CharField(max_length=300)),
                ('branch', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('comp', models.CharField(max_length=10000)),
                ('reqdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('program', models.CharField(max_length=300)),
                ('branch', models.CharField(max_length=300)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('feed', models.CharField(max_length=10000)),
                ('reqdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=225)),
                ('fname', models.CharField(max_length=225)),
                ('mname', models.CharField(max_length=225)),
                ('Gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('course', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='uploadLecture',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('Subject', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('Link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usm',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('New_file', models.FileField(upload_to='myimage')),
            ],
        ),
    ]
