# Generated by Django 5.1 on 2024-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0002_rename_subject_usm_subject_complaint_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=500)),
                ('enq', models.CharField(max_length=1000)),
                ('enqdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='noti',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('notim', models.CharField(max_length=251)),
                ('notidate', models.DateTimeField()),
            ],
        ),
    ]
