# Generated by Django 5.1 on 2024-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egyanportal', '0003_enquiry_noti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noti',
            name='notidate',
            field=models.CharField(max_length=30),
        ),
    ]
